# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Teléfono')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ciudad')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name_plural': 'Contactos',
                'verbose_name': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Recomendacións',
                'verbose_name': 'Recomendación',
            },
        ),
        migrations.CreateModel(
            name='HintGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Grupos de recomendaciones',
                'verbose_name': 'Grupo de recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Suscripciónes al Newsletter',
                'verbose_name': 'Suscripción al Newsletter',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('short_description', models.TextField(verbose_name='Descirpción')),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails', verbose_name='Icono')),
                ('featured', models.BooleanField(verbose_name='En promoción, el que lleve, el que escoja')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Imagen')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descirpción')),
                ('caption_on', models.BooleanField(verbose_name='Activar caption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
            options={
                'verbose_name_plural': 'ProductImages',
                'verbose_name': 'ProductImage',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Teléfono')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciónes',
                'verbose_name': 'Cotización',
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250, verbose_name='Producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Quote')),
            ],
            options={
                'verbose_name_plural': 'QuoteLines',
                'verbose_name': 'QuoteLine',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team/images')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Team')),
            ],
            options={
                'verbose_name_plural': 'Miembros del Equipo',
                'verbose_name': 'Miembro del Equipo',
            },
        ),
        migrations.AddField(
            model_name='hint',
            name='hint_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.HintGroup'),
        ),
    ]
